language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - jruby-19mode

env:
  matrix:
    - "DB=mysql    BUNDLE_WITHOUT=postgres:sqlite"
    - "DB=postgres BUNDLE_WITHOUT=mysql:sqlite"
  global:
    secure: "Cqu98Fne4YYtnVyn1WwuAt3yj9XdzayF/r6tEOwa7y7gzgS8/33XGUfcsCyU\nB9ywir3JCbMa+19wWrgBt4Mv+BcVsryRtbcIuZz303HBHis+yrG+AtM5rjM7\ng6IW7+BIMIvTWIlJ31q4MmjAeq4riNr7ZxTd9kHeQL3YTiLyKWk="

matrix:
  allow_failures:
    - rvm: jruby-19mode

before_script:
  - sh -c "cp config/database.$DB.yml config/database.yml"
  - sh -c "cp config/application.travis.yml config/application.yml"
  - sh -c "if [ \"$DB\" = 'postgres' ]; then psql -c 'create database jobsworth_test;' -U postgres; fi"
  - sh -c "if [ \"$DB\" = 'mysql' ];    then mysql -e 'create database jobsworth_test;'; fi"

script:
  - "bundle exec rake ci:build"

notifications:
  hipchat: <%= ENV['HIPCHAT_TOKEN'] %>@Procurementtool

# To stop Travis from running tests for a new commit,
# add the following to your commit message: [ci skip]
# You should add this when you edit documentation or comments, etc.
