---
javascripts:
- base:
  - prototype
  - jquery
  - jquery-ui
  - shadowbox
  - effects
  - dragdrop
  - controls
  - calendar
  - calendar-en
  - calendar-setup
  - application
  - jrails
  - cit
  - juggernaut_javascript
- portal:
  - prototype
  - tz
  - frontpage
stylesheets:
- base:
  - ui-lightness/jquery-ui
  - calendar-system
  - ui-datepicker
  - cit
- portal:
  - portal