---
javascripts:
- base:
  - prototype
  - jquery
  - jquery-ui
  - shadowbox
  - effects
  - dragdrop
  - controls
  - calendar
  - calendar-en
  - calendar-setup
  - application
  - jrails
- tt:
  - juggernaut_javascript
  - tt
- portal:
  - prototype
  - tz
  - frontpage
stylesheets:
- base:
  - scaffold
- portal:
  - portal
- tt:
  - calendar-system
  - ui.datepicker.css
  - tt
